### ISSUE TITLE
vertical and horizontal scrolling msg size

### ISSUE THREAD

**Issue by communistkiro** [jonbakke/boredserf#1]
Using both commits 84cc685 (current), and 9f3ccbd (yesterday) I get `boredserf: message too long: 3` on using keybindings for vertical and horizontal scrolling.
I feel like this may be a 1--2 character edit in the functions, but I'm too inexperienced to do a pull request.

**Comment by jonbakke** [comment]
I was able to re-create; [7488420](https://github.com/jonbakke/boredserf/commit/748842069d4c9b4727da497a1baecc2068d7ebb1) should have fixed it.

Yup, a 1 character edit. I messed up the greater-than/less-than logic when editing the style to make long lines more legible.

Thank you!
